version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mohdey17/reverseproxy
  backend_user:
    build:
      context: ../../udagram-c3-restapi-user
    image: mohdey17/udagram-c3-restapi-user
  backend_feed:
    build:
      context: ../../udagram-c3-restapi-feed
    image: mohdey17/udagram-c3-restapi-feed
  frontend:
    build:
      context: ../../udagram-c3-frontend
    image: mohdey17/udacity-c3-frontend
